### ISSUE TITLE
 math.floor() used to index array in geometries.py, line 73

### ISSUE THREAD

**Issue by KeyWeeUsr** [KeyWeeUsr/kivy3#1]
@kentborg posted, 2017-07-02T17:30:00Z:

> I deleted the floor() part and it no longer crashes.
> 
> But this is from a pretty old commit, makes me think I don't have the right code yet.
> 
> > 39bce596 kivy3/extras/geometries.py (Rense VanderHoek 2016-12-26 19:30:48 +0100 73)             > normal = self._cube_normals[floor(n_idx / 2)]
> 
> I am on master branch, at commit 8c664cca (2 Feb 2017), in https://github.com/KeyWeeUsr/kivy3.
> 
> -kb

**Comment by KeyWeeUsr** [comment]
What code triggered it? What was the error?

**Comment by kentborg** [comment]
[Sorry I originally  put the issue in the wrong place.]

I am running code I typed in from while watching https://www.youtube.com/watch?v=dz8hGKLdF1Y I can upload my version (it has at least one typo I haven't tracked down).

I see you have improved code on github, but still seems wrong to have an array index be a float.

kentborg@thinpan:~/python/kivy3-playing$ ./main4.py
[INFO   ] [Logger      ] Record log in /home/kentborg/.kivy/logs/kivy_17-07-02_1.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 13.0.6>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Shader      ] Read </usr/local/lib/python2.7/dist-packages/kivy3-0.1-py2.7.egg/kivy3/default.glsl>
 Traceback (most recent call last):
   File "./main4.py", line 413, in <module>
     My3D().run()
   File "/home/kentborg/python/kivy-git/kivy/app.py", line 802, in run
     root = self.build()
   File "./main4.py", line 287, in build
     cube_geo = BoxGeometry(.3, .3, .3)
   File "/usr/local/lib/python2.7/dist-packages/kivy3-0.1-py2.7.egg/kivy3/extras/geometries.py", line 60, in __init__
     self._build_box()
   File "/usr/local/lib/python2.7/dist-packages/kivy3-0.1-py2.7.egg/kivy3/extras/geometries.py", line 73, in _build_box
     normal = self._cube_normals[floor(n_idx / 2)]
 TypeError: list indices must be integers, not float

**Comment by KeyWeeUsr** [comment]
Damn, `floor()` returns a [float for float on py2](https://stackoverflow.com/q/3387655/5994041). Try to replace `floor()` just with `int()`.

**Comment by kentborg** [comment]
Putting in an int() works under Python 2.7.If it also does the right thing under Python 3, sounds like an easy fix.

Thanks,

-kb

**Comment by KeyWeeUsr** [comment]
Fixed in https://github.com/KeyWeeUsr/kivy3/commit/d0b710b79b3ab5f92c0401ea0fe64019d16533a3
